### ISSUE TITLE
Workflow BD Topo - Pblm from DB to DB

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#322]
I'm trying to exectute Geoclimate, with BD Topo, from our remote DB to our remote DB. So I'm using [this configuration file](https://github.com/orbisgis/geoclimate/blob/master/processingchain/src/test/resources/org/orbisgis/orbisprocess/geoclimate/processingchain/config/bdtopo_workflow_dbinput_dboutput.json) with these parameters

```json
    "input" : {
        "database": {
            "user": "xxxxxxx",
            "password": "xxxxxxx",
            "url": "jdbc:postgresql://xxxxxxx:5432/xxxxxxx",
            "id_zones":["56167"],
            "tables": {"iris_ge":"ign_iris.iris_ge_2016",
                "bati_indifferencie":"ign_bdtopo_2017.bati_indifferencie",
                "bati_industriel":"ign_bdtopo_2017.bati_industriel",
                "bati_remarquable":"ign_bdtopo_2017.bati_remarquable",
                "route":"ign_bdtopo_2017.route",
                "troncon_voie_ferree":"ign_bdtopo_2017.troncon_voie_ferree",
                "surface_eau":"ign_bdtopo_2017.surface_eau",
                "zone_vegetation":"ign_bdtopo_2017.zone_vegetation",
                "terrain_sport":"ign_bdtopo_2017.terrain_sport",
                "construction_surfacique":"ign_bdtopo_2017.construction_surfacique",
                "surface_route":"ign_bdtopo_2017.surface_route",
                "surface_activite":"ign_bdtopo_2017.surface_activite"}
        }
    },
    "output" :{
        "database": {
            "user": "xxxxxxx",
            "password": "xxxxxxx",
            "url": "jdbc:postgresql://xxxxxxx:5432/xxxxxxx",
            "tables": {"building_indicators":"building_indicators_2154_test_gwen",
                "block_indicators":"block_indicators_2154_test_gwen",
                "rsu_indicators":"rsu_indicators_2154_test_gwen",
                "rsu_lcz":"rsu_lcz_2154_test_gwen",
                "zones":"zones_2154_test_gwen"}
           }
    },
```
Then I execute in DBBeaver,

```groovy
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT')

import org.orbisgis.orbisprocess.geoclimate.Geoclimate
Geoclimate.logger = logger

def process = Geoclimate.Workflow.BDTOPO_V2()
process.execute(configurationFile:'/home/gpetit/geoclimate/bdtopo/config_bd_to_bd.json')
                   
logger.info process.results.outputMessage
```

Unfortunately, I have this messages

```
Reading file parameters from /home/gpetit/geoclimate/bdtopo/config_bd_to_bd.json
Example of configuration file to load data from a database and save the result into the same database
null
Groovy script successfully executed.
```

I removed my `.groovy` folder, and the problem is the same

Any idea @ebocher @SPalominos ?

**Comment by j3r3m1** [comment]
ok I try it and let you know

**Comment by j3r3m1** [comment]
seems there is a problem with the database as input. It is supposed to work both only with a database as output or with a database AND a folder. However, none of them work while it works when using the output folder alone... I have tried to investigate this in the code but I would need to make some tests and the ones used by @ebocher seem empty (I think he has local files). We should share those ones in order to make testing in IntelliJ

**Comment by gpetit** [comment]
I made a test with the current SNAPSHOT to see if the last PRs resolved this issue, but unfortunately no.
Still the same (non) error

```
!ENTRY groovy.lang.GroovyShell 1 0 2020-04-21 15:47:45.726
!MESSAGE null

!ENTRY org.orbisgis.ui.editors.groovy.GroovyJob 1 0 2020-04-21 15:47:45.727
!MESSAGE Groovy script successfully executed.
```

**Comment by ebocher** [comment]
I'm on it

**Comment by ebocher** [comment]
Fixed

**Comment by gpetit** [comment]
Thx. It works (even if I still have a problem. I will open a new issue)
