### ISSUE TITLE
OSM download when ' character

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#352]
There is trouble with the downloading of cities having ' in its name (such as Montfort-l**'**Amaury or Le Plessis-**l**'Évêque).
The error message is the following:
> [INFO] org.orbisgis.orbisanalysis.osm.utils.Utilities - https://nominatim.openstreetmap.org/search?q=Montfort-l%27Amaury&limit=5&format=geojson&polygon_geojson=1
[INFO] org.orbisgis.orbisanalysis.osm.utils.Utilities - Executing query... Montfort-l'Amaury
[INFO] org.orbisgis.orbisanalysis.osm.utils.Utilities - Downloading the Nominatim data.
[ERROR] org.orbisgis.orbisdata.processmanager.process.Process - Error while executing the process.
java.lang.IllegalStateException: Failed to process query. Unterminated ' character?
	at groovy.sql.ExtractIndexAndSql.appendToEndOfString(ExtractIndexAndSql.java:145)

**Comment by ebocher** [comment]
Thanks move to https://github.com/orbisgis/orbisanalysis/issues/62

**Comment by ebocher** [comment]
Fixed

**Comment by j3r3m1** [comment]
still does not work with the same error. @ebocher did you try it from outside geoclimate ?

**Comment by ebocher** [comment]
I'm on it

**Comment by ebocher** [comment]
Fixed
